Added checkstyle to pre-commit hooks

diff --git a/gitHooks/scripts/javaPreCommit b/gitHooks/scripts/javaPreCommit
--- a/gitHooks/scripts/javaPreCommit
+++ b/gitHooks/scripts/javaPreCommit
@@ -8,6 +8,7 @@ fi
 
 #prevents the shell from aborting if maven returns a non zero exit code
 set +e
+
 echo Checking spotless
 mvn spotless:check &> /dev/null
 exitCode=$?
@@ -15,5 +16,17 @@ exitCode=$?
 if [ $exitCode -gt 0 ]
 then
 	echo "Spotless failed. Please run 'mvn spotless:apply' to fix."
+	exit 1
 fi
-exit $exitCode
+
+echo Running Checkstyle
+mvn checkstyle:check &> /dev/null
+exitCode=$?
+
+if [ $exitCode -gt 0 ]
+then
+  echo "Checkstyle failed. Please run 'mvn checkstyle:check' to get a list of issues."
+  exit 1
+fi
+
+exit 0
